### ISSUE TITLE
Ext shortcuts: automatic alternatives

### ISSUE THREAD

**Issue by gene-pavlovsky** [wise0704/FlashDevelop#7]
Is it necessary to enter alternatives like "Ctrl-E Q; Ctrl-E Ctrl-Q"? In my opinion, configuring a shortcut as Ctrl-E Q should support both Ctrl-E Q and Ctrl-E Ctrl-Q automatically. It is the case with Visual Studio

**Comment by wise0704** [comment]
Visual Studio behaves the same way as mine. 
The default shortcut file having the two combinations was to match with VS. 
For example, (in VS) `Edit.CommentSelection` has both `Ctrl+E, C` and `Ctrl+E, Ctrl+C` assigned. If you remove one, only the other will work. 

Although it kind of makes the shortcut dialog look a bit messy, making `Ctrl+E, C` also match `Ctrl+E, Ctrl+C` will really complicate the code, and also potentially prevent users who want to differentiate the two from doing so.
 - If pressing `Ctrl+E, Ctrl+C` triggers `Ctrl+E, C`, should `Ctrl+E, Ctrl+Shift+C` trigger `Ctrl+E, Shift+C` too? What about pressing `Ctrl+E, Shift+C` - should it trigger `Ctrl+E, Ctrl+Shift+C`?
 - `Ctrl+Alt+Shift+E, C` will really be tricky. It will potentially match `C`, `Ctrl+C`, `Ctrl+Alt+C`, etc.

**Comment by gene-pavlovsky** [comment]
Ok, I've checked VS again and it seems I was wrong. I missed the combo box with multiple hotkeys.
I agree that it might get too complicated and un-intuitive if following my suggestions.
