### ISSUE TITLE
ClipboardHistoryDialog: Add ability to copy selected item to clipboard

### ISSUE THREAD

**Issue by gene-pavlovsky** [wise0704/FlashDevelop#8]
I'd like to request a feature.
Sometimes I want to use some item from clipboard history outside of FlashDevelop.

Unfortunately, ClipboardHistoryDialog:
- Doesn't have a "Copy" button
- Doesn't allow to Ctrl+C or Right-Click&Copy the currently selected item display either from list view or from text view

Please, add some (or all of the above) option(s) to copy the item to clipboard.

**Comment by wise0704** [comment]
https://github.com/fdorg/flashdevelop/pull/1670

**Comment by gene-pavlovsky** [comment]
감사합니다
